network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s3:
      dhcp4: no
      link-local: []
    eth0:
      dhcp4: true
      dhcp4-overrides:
        route-metric: 100
      dhcp6: false
      match:
        driver: hv_netvsc
        macaddress: <interface_mac>
      set-name: eth0

  bridges:
    br-int:
      openvswitch:
        protocols: [OpenFlow13]
        other-config:
          datapath-id: 0000000000000006
        controller:
          addresses: [tcp:<interface_ip>:31653]

    br1:
      openvswitch: {}
      interfaces: [eth0]
      addresses: [<interface_ip>/24]
      routes:
        - to: default
          via: <default_gateway>
      nameservers:
       addresses: [8.8.8.8]