apiVersion: v1
kind: Pod
metadata:
  name: iperf2-server
  labels:
    app: iperf2-server
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      { "name": "n3network", "interface": "n3", "ips": [ "10.10.3.233/24" ] }
      ]'
spec:
  # nodeSelector:
  #   kubernetes.io/hostname: <node-name>
  containers:
  - name: iperf2-server
    image: ubuntu
    command: ["/bin/sh"]
    args:
    - "-c"
    - "apt-get update && apt-get install -y iperf iputils-ping net-tools iproute2 tcpreplay && \
    ip route add 10.41.0.0/24 via 10.10.3.1 dev n3 && \
    while true; do sleep 30; done"
    ports:
    - containerPort: 5001
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]